// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fblundpnpeamrowjexpy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZibHVuZHBucGVhbXJvd2pleHB5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg1ODgyNDYsImV4cCI6MjA1NDE2NDI0Nn0.wd6kgIHULw6f73K5B98SZxAixZQmMVNO4kQnpaPpR-4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);